name: Pre release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          scope: '@bna'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: HUSKY_SKIP_HOOKS=1  yarn lerna publish prerelease --preid next --dist-tag next --create-release github -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
